### ISSUE TITLE
Action - Kubernetes change resources

### ISSUE THREAD

**Issue by proman3419** [k8loud/themis-executor#78]
There should be a possibility to modify resources' values:
```
resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 500m
    memory: 500Mi
```
